export const WITHDRAWAL_REQUEST = "WITHDRAWAL_REQUEST";
export const WITHDRAWAL_SUCCESS = "WITHDRAWAL_SUCCESS";
export const WITHDRAWAL_FAILURE = "WITHDRAWAL_FAILURE";

export const WITHDRAWAL_PROCESS_REQUEST = "WITHDRAWAL_PROCESS_REQUEST";
export const WITHDRAWAL_PROCESS_SUCCESS = "WITHDRAWAL_PROCESS_SUCCESS";
export const WITHDRAWAL_PROCESS_FAILURE = "WITHDRAWAL_PROCESS_FAILURE";

export const GET_WITHDRAWAL_HISTORY_REQUEST = "GET_WITHDRAWAL_HISTORY_REQUEST";
export const GET_WITHDRAWAL_HISTORY_SUCCESS = "GET_WITHDRAWAL_HISTORY_SUCCESS";
export const GET_WITHDRAWAL_HISTORY_FAILURE = "GET_WITHDRAWAL_HISTORY_FAILURE";

export const GET_WITHDRAWAL_REQUEST_REQUEST = "GET_WITHDRAWAL_REQUEST_REQUEST";
export const GET_WITHDRAWAL_REQUEST_SUCCESS = "GET_WITHDRAWAL_REQUEST_SUCCESS";
export const GET_WITHDRAWAL_REQUEST_FAILURE = "GET_WITHDRAWAL_REQUEST_FAILURE";

export const ADD_PAYMENTDETAILS_REQUEST = "ADD_PAYMENTDETAILS_REQUEST";
export const ADD_PAYMENTDETAILS_SUCCESS = "ADD_PAYMENTDETAILS_SUCCESS";
export const ADD_PAYMENTDETAILS_FAILURE = "ADD_PAYMENTDETAILS_FAILURE";

export const GET_PAYMENTDETAILS_REQUEST = "GET_PAYMENTDETAILS_REQUEST";
export const GET_PAYMENTDETAILS_SUCCESS = "GET_PAYMENTDETAILS_SUCCESS";
export const GET_PAYMENTDETAILS_FAILURE = "GET_PAYMENTDETAILS_FAILURE";
